language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
script:
  - npm test
  - npm run build
deploy:
  provider: heroku
  skip_cleanup: true
  api_key: $HEROKU_API_KEY 
  app: sliit-industrial-training 
  on:
    branch: master